App_Portfolio/urls.py
from django.urls import path
from .import views

app_name = 'App_Portfolio'


urlpatterns = [
	path('', views.home, name="home"),
	path('project-list', views.list, name="list"),
	path('project_detail/<str:pk>/', views.project_detail, name="project-detail"),
	path('contact', views.contact, name="contact"),

]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.apiOverview, name="api-overview"),
    path('project-list/', views.projectList, name="project-list"),
	path('project-detail/<int:pk>/', views.projectDetail, name="project-detail"),
	path('project-create/', views.projectCreate, name="project-create"),
	
	path('project-update/<str:pk>/', views.projectUpdate, name="project-update"),
	path('project-delete/<str:pk>/', views.projectDelete, name="project-delete"),

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('App_Portfolio.urls')),

    re_path(r'^favicon\.ico$', favicon_view),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App_Portfolio/models.py
from django.db import models

# Create your models here.

api/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
  title = models.CharField(max_length=200)
  image = models.ImageField(blank=True, null=True, upload_to='project')
  description = models.TextField()
  completed = models.BooleanField(default=False, blank=True, null=True)
  github = models.URLField(blank=True)
  web = models.URLField(blank=True)
  
      
  def __str__(self):
    return self.title

App_Portfolio/forms.py
from django import forms


# forms


class mail_form(forms.Form):
    name = forms.CharField(widget=forms.CharField(
        attrs={'class': 'name in-box-input row1','placeholder': 'Name'}), label='')
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'email-field in-box-input row1','placeholder': 'Email'}), label='')
    number = forms.IntegerField(widget=forms.IntegerField(
        attrs={'class': 'number-field in-box-input row1','placeholder': 'number'}), label='')
    subject = forms.CharField(widget=forms.CharField(
        attrs={'class': 'subject-field in-box-input row1','placeholder': 'Subject'}), label='')
    message = forms.Textarea(widget=forms.Textarea(
        attrs={'class': 'message-field in-box-input row2','placeholder': 'message'}), label='')

App_Portfolio/views.py
from django.http import response
from django.shortcuts import get_object_or_404, render
from django.core.mail import BadHeaderError, send_mail
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import RequestContext, context

import requests

from api.models import Project

# Create your views here.


def home(request):
    return render(request, 'project/home.html',)


def list(request):
    response = requests.get(
        'https://akash-portfolio-21.herokuapp.com/api/project-list/')
    data = response.json()
    context = {
        'data': data,
    }

    return render(request, 'project/list.html', context)


def project_detail(request, pk):
    # project = Project.objects.get(pk=pk)
    project = get_object_or_404(Project, pk=pk)
    # print(project[0].title)
    # response = requests.get('http://127.0.0.1:8000/api/project-detail/pk/')
    # project = response
    # print(project.image)
    # print(project.description)

    context = {
        'project': project,
    }

    return render(request, 'project/project_detail.html', context)



def contact(request):
    success_msg = ''
    if request.method == 'POST':
        name = request.POST.get('name', '')
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')
        from_email = request.POST.get('from_email', '')
    
        send_mail(subject, message, from_email, ['akashdemo1234@gmail.com'], fail_silently=False)
        context = {
            'name' : name,
            'success_msg' : "successfully send your email",
        }
        return render(request, 'project/contact.html', context)
    else:
        return render(request, 'project/contact.html', context = { 'success_msg' : success_msg})

        

    
    

api/views.py
from django.shortcuts import render
from django.http import JsonResponse

from rest_framework.decorators import api_view
from rest_framework.response import Response

from .serializers import ProjectSerializer

from .models import Project


@api_view(['GET'])
def apiOverview(request):
	api_urls = {
		'List':'/project-list/',
		'Detail View':'/project-detail/<str:pk>/',
		'Create':'/project-create/',
		'Update':'/project-update/<str:pk>/',
		'Delete':'/project-delete/<str:pk>/',
		}

	return Response(api_urls)


    # return JsonResponse("api base view", safe=False)           #  testing

@api_view(['GET'])
def projectList(request):
	project = Project.objects.all().order_by('-id')
	serializer = ProjectSerializer(project, many=True)
	return Response(serializer.data)

@api_view(['GET'])
def projectDetail(request, pk):
	project = Project.objects.get(id=pk)
	serializer = ProjectSerializer(project, many=False)
	return Response(serializer.data)


@api_view(['POST'])
def projectCreate(request):
	serializer = ProjectSerializer(data=request.data)

	if serializer.is_valid():
		serializer.save()
   
	return Response(serializer.data)

@api_view(['PUT'])
def projectUpdate(request, pk):
	project = Project.objects.get(id=pk)
	serializer = ProjectSerializer(instance=project, data=request.data)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)

@api_view(['DELETE'])
def projectDelete(request, pk):
	project = Project.objects.get(id=pk)
	project.delete()

	return Response('Item succsesfully delete!')

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
     
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Lato:ital@1&display=swap" rel="stylesheet"> 
     
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

     <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
     
      <title>{% block title_block %} Portfolio | Akash {% endblock %}</title>

  {% block css_block %}
  
  {% endblock %}
  
  </head>

  <body>
  {% include 'navbar.html' %}
  <div class="container">
      <div class="messages container mt-2">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>

    {% block body_block %} {% endblock %}

  </div>
  <div class="foot">
    {% include 'footer.html' %}
    
  </div>
  
  

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

templates/footer.html
{% load static %}

<style>
    footer {
        background: rgba(0,0,0,.85);
        height: auto;
        width: 100vw;
        /* font-family: ; */
        margin-top: 6rem;
        padding-top: 20px;
        color: #fff;
    }
    .footer-content{
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        text-align: center;
    }
    /* social ul li..........................................  */

    /* .socials li{
        list-style: none;
        float: left;
    }
    .socials li a{
        position: relative;
        width: 50px;
        height: 50px;
        background: #e9f5ff;
        color: #2fa1ff;
        margin: 0 5px;
        display: flex;
        justify-content: center;
        align-items: center;
        text-decoration: none;
        border-radius: 50%;
        font-size: 20px;
        transition: 0.5s;
    }
    .socials li a:hover{
        color: #fff;
    }
    .socials li a .fa,
    .socials li a .fab{
        position: relative;
        z-index: 1000;
    }
    .socials li a::before{
        content: '';
        position: absolute;
        width: 100%;
        height: 100%;
        background: #2fa1ff;
        border-radius: 50%;
        transform: scale(0);
        transition: 0.5s;
    }
    .socials a:nth-child(1)::before {
        background: #3b5998;
    }
    .socials a:nth-child(2)::before {
        background: #AEB5BB;
    }

    .socials li a:hover:before{
        transform: scale(1);
    } */
    
    /* social ul li..........................................end  */


    .socials {
        float: left;
    }
    .socials  a{
        position: relative;
        width: 40px;
        height: 40px;
        background: #e9f5ff;
        color: #2fa1ff;
        margin: 0 5px;
        display: flex;
        justify-content: center;
        align-items: center;
        text-decoration: none;
        border-radius: 50%;
        font-size: 20px;
        transition: 0.5s;
        float: left;
    }
    .socials a:hover{
        color: #fff;
    }
    .socials  a .fa,
    .socials a .fab{
        position: relative;
        z-index: 1000;
    }
    .socials  a::before{
        content: '';
        position: absolute;
        width: 100%;
        height: 100%;
        /* background: #2fa1ff; */
        border-radius: 50%;
        transform: scale(0);
        transition: 0.5s;
    }
    .socials a:nth-child(1)::before {
        background: #3b5998;
    }
    .socials a:nth-child(2)::before {
        background: #AEB5BB;
    }
    .socials a:nth-child(3)::before {
        background: #007bb5;
    }
    .socials a:nth-child(4)::before {
        background: #ea4c89;
    }

    .socials  a:hover:before{
        transform: scale(1);
    }


</style>

<footer class="footer-body">
    <div class="footer-content">
        <h3 style="margin-bottom: 20px;">Akash | Portfolio</h3>
        <!-- <img src="{% static 'profile/Logo.png' %}" width="50" height="50" style="margin-top: -6px;  margin-bottom: 20px;" class="d-inline-block align-top" alt="Akash Logo"> -->
        <!-- <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iure rem cum, libero dolor repellat at.</p> -->

        <!-- <ul class="socials">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fab fa-github"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
        </ul> -->

        <div class="socials">
            <a href="https://www.facebook.com/munazermontasir.akash" target="_blank"><i class="fa fa-facebook"></i></a>
            <a href="https://github.com/AKASH-2019"  target="_blank"><i class="fab fa-github"></i></a>
            <a href="https://www.linkedin.com/in/munazer-montasir-akash-a3514a1b9/"  target="_blank"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
        </div>
        <div class="footer-bottom">
            <p>copyright &copy;2021. Designed by <span>Akash.</span></p>
        </div>
    </div>
</footer>

templates/navbar.html
{% load static %}

<style>
  .dyn-nav {
    background-color: #fff;
  }

  .custom-toggler.navbar-toggler {
    /* border-color: rgb(255, 102, 203); */
    /* border-color: rgb(54,217,182); */
    border-color: rgba(0,0,0,.3);
  }

  .custom-toggler .navbar-toggler-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0,0,0,.15)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");
  }
</style>

<nav class="navbar navbar-expand-lg  dyn-nav">
  <div class="container">
    <!-- <a class="navbar-brand" style="color: rgb(54,217,182); font-weight: 700; font-size: 1.5rem;" href="{% url 'App_Portfolio:home' %}">AKASH</a> -->
    <a class="navbar-brand" href="{% url 'App_Portfolio:home' %}">
      <img src="{% static 'profile/Logo.png' %}" width="30" height="30" style="margin-top: 3.5px;" class="d-inline-block align-top" alt="Akash Logo">
      <span style="color: rgb(54,217,182); font-weight: 700; font-size: 1.5rem; margin-left: 5px;">Akash</span>
    </a>
    <button type="button" class="navbar-toggler navbar-toggler-right custom-toggler" data-toggle="collapse"
      data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
        class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">

        <li class="nav-item mr-5">
          <!-- <a href="#" class="btn btn-primary">Project</a> -->
          <a href="{% url 'App_Portfolio:list' %}" class="btn">Portfolio</a>
        </li>

        <li class="nav-item">
          <!-- <a href="#" class="btn btn-primary">Login</a> -->
          <a href="{% url 'App_Portfolio:contact' %}" class="btn">Contact</a>
        </li>


      </ul>
    </div>
  </div>
</nav>

templates/project/home.html
{% extends 'base.html' %}
{% load static %}


{% block title_block %} Portfolio | Akash {% endblock %}

{% block css_block %}

<style>
    body {
        background: rgba(54, 217, 182, .50);
        font-family: "Lato", sans-serif;
        font-weight: 400;
        line-height: 1.7;
    }

    .section-stories {
        margin-top: 4rem;
    }

    .story {
        top: 20%;
        width: 75%;
        margin: 0 auto;
        box-shadow: 0 3rem 6rem rgba(0, 0, 0, .25);
        background-color: #fff;
        border-radius: 3px;
        padding: 3rem 4rem 3rem 1.5rem;
        font-size: 1.2rem;

    }

    .story__shape {
        width: 13rem;
        height: 13rem;
        float: left;
        -webkit-shape-outside: circle(50% at 50% 50%);
        shape-outside: circle(50% at 50% 50%);
        -webkit-clip-path: circle(50% at 50% 50%);
        clip-path: circle(50% at 50% 50%);
        /* transform: translateX(-3rem) skewX(12deg); */
        position: relative;
    }

    .story__img {
        height: 100%;
        border: red;
    }

    .story__text {

        position: relative;
        top: 1rem;
        left: 2.2rem;
    }

    .story__text p {
        font-family: 'Lato', sans-serif;
    }

    @media(max-width:765px) {


    }

    .text-center {
        text-align: center i !important;
    }



    .text-center {
        text-align: center i !important;
    }

    .text-left {
        text-align: left i !important;
    }

    .text-right {
        text-align: right i !important;
    }

    .footer__link:link,
    .footer__link:visited {
        color: black;
        font-weight: bold;
        /* background-color: #333; */
        text-decoration: none;
        /* text-transform: uppercase; */
        display: inline-block;
        transition: all .2s;
    }

    /* .footer__link:hover,
    .footer__link:active {
        color: #55c57a;
        box-shadow: 0 1rem 2rem rgba(0, 0, 0, 0.4);
        transform: rotate(5deg) scale(1.3);
    } */

</style>

{% endblock %}



{% block body_block %}

<section class="section-stories">
    <div class="row">
        <div class="story">
            <figure class="story__shape">
                <img src="{% static 'profile/akash3.jpg' %}" alt="Profile Image" class="story__img">
                <figcaption class="story__caption">Mary Smith</figcaption>
            </figure>
            <div class="story__text">
                <!-- <h3 class="heading-tertiary u-margin-buttom-small">I had the best week ever with my family</h3> -->
                <p>
                    Assalamualaikum Warahmatulla…. My self <a href="#" class="footer__link">Munazer Montasir AKash</a>.
                    I am from Chattogram, Bangladesh. I have completed my graduation from IIUC in Bsc in CSE. I am a
                    person who is positive about every aspect of life.
                    <br>
                    I would like to introduce myself as a programmer. I have good experience of problem-solving in
                    different online judge by different languages. I am proficient in C, C++, JavaScript, R, and Python.
                    I am also a full-stack web developer. I would build a Web Application using Python, Django Web
                    Framework. I have well experienced in using the Django Rest Framework REST-based solutions for
                    back-ends. I also use HTML, CSS, Bootstrap4, and JavaScript for the front end to ensure the Web app
                    looks attractive. 😊
                </p>
            </div>
        </div>

    </div>
</section>


{% endblock %}

templates/project/list.html
{% extends 'base.html' %}

{% block title_block %} Portfolio | Project {% endblock %}

{% block css_block %}

<style>
    body {
        background: rgba(54, 217, 182, .50);
        font-family: 'Lato', sans-serif;
    }


    .section-title {
        flex: 0 0 100%;
        max-width: 100%;
        margin-top: 30px;
        margin-bottom: 50px;
    }

    .section-title h1 {
        display: inline-block;
        font-size: 50px;
        text-transform: uppercase;
        color: #302d2d;
        margin: 0 0 10px;
        position: relative;
        padding-bottom: 14px;
    }

    /* .section-title h4{
    font-size: 20px;
    color: #423940;
    position: relative;
    padding-bottom: 14px;
} */
    .section-title h1::before {
        content: '';
        height: 6px;
        /* background-color: #ff0000; */
        background-color: #fdf9ff;
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100px;
        right: 0;
        margin: auto;
    }

    .text-center {
        text-align: center i !important;
    }

    .text-left {
        text-align: left i !important;
    }

    .text-right {
        text-align: right i !important;
    }


    .portfolio {
        /* background-color: #fdf9ff; */
        padding-bottom: 50px;
        /* min-height: 120vh; */
    }

    .portfolio .portfolio-item {
        flex: 0 0 33.33%;
        max-width: 33.33%;
        position: relative;
        padding: 8px;
        margin-bottom: 8px;
    }

    .portfolio .portfolio-inner-item {
        border: 6px solid #4e4e4e;
        /* border: 6px solid rgb(54,217,182); */
        border-radius: 10px;
        overflow: auto;
        position: relative;
        cursor: pointer;

    }

    .portfolio .portfolio-inner-item .portfolio-img img {
        width: 100%;
        height: 200px;
        display: block;
    }

    .portfolio .portfolio-item .portfolio-info {
        position: absolute;
        left: 0;
        top: 0;
        background-color: rgba(0, 0, 0, 0.8);
        height: 100%;
        width: 100%;
        z-index: 1;
        padding-top: 100px;
        transition: all .5s ease;
        opacity: 0;
    }

    .portfolio .portfolio-inner-item:hover .portfolio-info {
        opacity: 1;
    }

    .portfolio .portfolio-item .portfolio-info h4 {
        font-size: 18px;
        font-weight: 700;
        color: #f5f5f5;
        text-transform: capitalize;
        transition: all .7s ease;
        transform: translateX(-20px);
        opacity: 0;
    }

    .portfolio .portfolio-item .portfolio-info h4>a {
        text-decoration: none;
        color: #f5f5f5;
    }

    .portfolio .portfolio-inner-item:hover .portfolio-info h4 {
        opacity: 1;
        transform: translateX(0);
    }


    /* Responsive section */
    @media(max-width:991px) {
        

        .portfolio .portfolio-item {
            flex: 0 0 50%;
            max-width: 50%;
            position: relative;
            padding: 8px;
        }
    }

    @media(max-width:767px) {
        .section-title h1 {
            font-size: 40px;
        }

        .portfolio .portfolio-item {
            flex: 0 0 50%;
            max-width: 50%;
            position: relative;
            padding: 8px;
        }
    }

    @media(max-width:500px) {
        .section-title h1 {
            font-size: 30px;
        }

        .portfolio .portfolio-item {
            flex: 0 0 100%;
            max-width: 100%;
            position: relative;
        }
    }
</style>

{% endblock %}



{% block body_block %}

<section class="portfolio" id="portfolio">
    <div class="container">
        <div class="row">
            <div class="section-title text-center">
                <h1>My Portfolio</h1>
                <!-- <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis voluptatum maxime culpa vitae.</h4> -->
            </div>
        </div>
        <div class="row">

            {% for project in data %}
            <div class="portfolio-item">
                <div class="portfolio-inner-item">
                    <div class="portfolio-img">
                        <img src="{{project.image}}" alt="{{project.title}}">
                    </div>
                    <div class="portfolio-info text-center">
                        <h4><a href="{% url 'App_Portfolio:project-detail' pk=project.id %}">{{project.title}}</a></h4>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>



{% endblock %}

templates/project/project_detail.html
{% extends 'base.html' %}

{% block title_block %} Portfolio | Project-detail {% endblock %}

{% block css_block %}

<style>
    body {
        font-family: 'Lato', sans-serif;
        background: rgba(54, 217, 182, .50);
    }

    .project-detail {
        padding-bottom: 50px;
        min-height: 90vh;
    }

    .card {
        position: absolute;
        top: 65%;
        left: 50%;
        transform: translate(-50%, -50%);
        height: 32rem;
        width: 23rem;
        border-radius: 10px;
    }

    .card-img-top {
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.5);
        text-align: center;
        display: flex;
        border-top-right-radius: 10px;
        border-top-left-radius: 10px;
    }

    .card-body {
        text-align: center;
        box-shadow: 0px 15px 15px -8px rgba(0, 0, 0, 0.5)
    }

    .card-body h6 {
        font-size: 14px;
        text-transform: uppercase;
        color: deeppink;
    }

    .card-title {
        text-transform: uppercase;
        font-weight: bold;
        font-size: 24px;
    }

    .soc {
        position: relative;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .soc a {
        position: relative;
        width: 40px;
        height: 40px;
        background: #e9f5ff;
        color: #2fa1ff;
        margin: 0 5px;
        display: flex;
        justify-content: center;
        align-items: center;
        text-decoration: none;
        border-radius: 50%;
        font-size: 20px;
        transition: 0.5s;
        float: left;
    }

    .soc a:hover {
        color: #fff;
    }

    .soc a .fa,
    .soc a .fab {
        position: relative;
        z-index: 1000;
    }

    .soc a::before {
        content: '';
        position: absolute;
        width: 100%;
        height: 100%;
        border-radius: 50%;
        transform: scale(0);
        transition: 0.5s;
    }

    .soc a:nth-child(1)::before {
        background: #AEB5BB;
    }

    .soc a:nth-child(2)::before {
        background: #ea4c89;
    }

    .soc a:hover::before {
        transform: scale(1);
    }

    .text-center {
        text-align: center i !important;
    }

    .text-left {
        text-align: left i !important;
    }

    .text-right {
        text-align: right i !important;
    }

    /* responsive design */
    @media(max-width:767px) {

        .card {
            position: absolute;
            top: 75%;
            left: 50%;
            transform: translate(-50%, -50%);
            height: 28rem;
            width: 18rem;
            border-radius: 10px;
        }

        .card-body h6 {
            font-size: 12px;
        }

        .card-title {
            font-size: 20px;
        }
    }
    @media(max-width:500px) {
        .card {
            position: absolute;
            top: 75%;
            left: 50%;
            transform: translate(-50%, -50%);
            height: 28rem;
            width: 18rem;
            border-radius: 10px;
        }
    }
</style>

{% endblock %}



{% block body_block %}

<section class="project-detail" id="project-detail">
    <div class="card text-center">
        <img class="card-img-top" src="{{project.image.url}}" alt="{{project.title}}">
        <div class="card-body">
            <h5 class="card-title">{{project.title}}</h5>
            <p class="card-text">{{project.description}}</p>
            <div class="soc">
                <!-- <a href="#"><i class="fa fa-facebook"></i></a> -->
                {% if project.github %}
                <a href="{{project.github}}" target="_blank"><i class="fab fa-github"></i></a>
                {% else %}
                <a href="#"><i class="fab fa-github"></i></a>
                {% endif %}
                <!-- <a href="#"><i class="fa fa-linkedin"></i></a> -->
                {% if project.web %}
                <a href="{{project.web}}" target="_blank"><i class="fa fa-dribbble"></i></a>
                {% else %}
                <a href="#"><i class="fa fa-dribbble"></i></a>
                {% endif %}

            </div>
        </div>
    </div>
</section>



{% endblock %}